version: "3"

services:

  gitserver:
    image: volnenko/gitserver:latest
    ports:
      - "8080:8080"
    environment:
      SECURITY_ENABLED: "false"
      SECURITY_USERNAME: "admin"
      SECURITY_PASSWORD: "admin"
      S3_ENDPOINT: http://minio:9000/
      S3_BUCKET: gitserver
      S3_CLIENT_ID: minio
      S3_SECRET_KEY: minio
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio
      MINIO_DEFAULT_BUCKETS: gitserver
    command: server /data --console-address ":9001"
    restart: unless-stopped